### 상품 단건 조회
GET http://localhost:8080/api/v1/products/1763442256744_8e7b17bd-5668-4db5-aa45-9a67c41fb8c6
Content-Type: application/json

### 상품 페이징 조회
GET http://localhost:8080/api/v1/products?page=0&size=10&sort=productId,asc
Content-Type: application/json

### 주문 생성
POST http://localhost:8080/api/v1/orders
Content-Type: application/json

{
  "customerId": 1,
  "orderItems": [
    {
      "productId": "1763442255911_a0895045-6ff6-47aa-8b1f-8d3fd331d288",
      "quantity": 3
    }
  ],
  "paymentMethod": "CREDIT_CARD"
}

### 결제 완료
POST http://localhost:8080/api/v1/orders/1/payment
Content-Type: application/json

{
  "success": true
}

### 결제 실패
POST http://localhost:8080/api/v1/orders/2/payment
Content-Type: application/json

{
  "success": false
}

### 주문 완료
POST http://localhost:8080/api/v1/orders/1/complete

### 주문 취소
POST http://localhost:8080/api/v1/orders/2/cancel