### 상품 단건 조회
GET http://localhost:8080/api/v1/products/1763599154947_3fd565db-dc6c-4c7d-9a79-77c43a7c806e
Content-Type: application/json

### 상품 페이징 조회
GET http://localhost:8080/api/v1/products?page=0&size=10&sort=productId,asc
Content-Type: application/json

### 주문 생성
POST http://localhost:8080/api/v1/orders
Content-Type: application/json

{
  "customerId": 1,
  "orderItems": [
    {
      "productId": "1763599154947_3fd565db-dc6c-4c7d-9a79-77c43a7c806e",
      "quantity": 3
    }
  ],
  "paymentMethod": "CREDIT_CARD"
}

### 결제 완료
POST http://localhost:8080/api/v1/orders/3/payment
Content-Type: application/json

{
  "success": true
}

### 결제 실패
POST http://localhost:8080/api/v1/orders/4/payment
Content-Type: application/json

{
  "success": false
}

### 주문 완료
POST http://localhost:8080/api/v1/orders/3/complete

### 주문 취소
POST http://localhost:8080/api/v1/orders/4/cancel